### ISSUE TITLE
一直报错无法使用

### ISSUE THREAD

**Issue by G2Wyn** [Ccccx159/Emby_Notifier#1]
[2024-05-17 16:40:54] [my_httpd.py|worker|8] [INFO] : Emby Notifier started.
[2024-05-17 16:40:54] [my_httpd.py|my_httpd|58] [INFO] : HTTP server started at http://localhost:8000
[2024-05-17 16:41:01] [media.py|process_media|214] [INFO] : Received message: Test Notification
[2024-05-17 16:41:01] [media.py|process_media|216] [WARNING] : Unsupported event type: system.notificationtest

**Comment by Ccccx159** [comment]
> [2024-05-17 16:40:54] [my_httpd.py|worker|8] [INFO] : Emby Notifier started. [2024-05-17 16:40:54] [my_httpd.py|my_httpd|58] [INFO] : HTTP server started at http://localhost:8000 [2024-05-17 16:41:01] [media.py|process_media|214] [INFO] : Received message: Test Notification [2024-05-17 16:41:01] [media.py|process_media|216] [WARNING] : Unsupported event type: system.notificationtest

从这段日志中无法得到任何 ERROR 信息，请提供一下信息：
1. Emby Notifier 的版本号
2. Emby Server 的版本号
3. 运行的命令
4. 贴出 ERROR 部分报错日志，可以的话，请将 LOG_LEVEL 设置为 DEBUG，并贴出完整日志（请注意信息脱敏）

谢谢~

**Comment by G2Wyn** [comment]
NOtifier是docker得最新版
EMBY是4.8.3.0
使用的docker compost命令是：
version: '3'
services:
  emby_notifier_tg:
    build:
      context: .
      dockerfile: dockerfile
    image: b1gfac3c4t/emby_notifier_tg:latest
    environment:
      - TZ=Asia/Shanghai
      # 这里所有的环境变量都不要使用引号
      # 必填参数
      - TMDB_API_TOKEN=<c57551111bcb554f>
      - TVDB_API_KEY=<BA7E1111B103>
      - TG_BOT_TOKEN=<69831111111EFCS8Q>
      - TG_CHAT_ID=<-100111111500>
      # 可选参数
      - LOG_LEVEL=DEBUG # [DEBUG, INFO, WARNING] 三个等级，默认 INFO
      - LOG_EXPORT=False # [True, False0] 是否将日志输出到文件，默认 False
      - LOG_PATH=/var/tmp/emby_notifier_tg/ # 默认 /var/tmp/emby_notifier_tg/
    network_mode: "bridge"
    ports:
      - "8000:8000"
    restart: unless-stopped
    

Debug日志是：
Checking environment variables...
emby_notifier_tg_1  | TMDB_API_TOKEN: (req) <c154f>
emby_notifier_tg_1  | TVDB_API_KEY:   (req) <BA7E15A91B103>
emby_notifier_tg_1  | TG_BOT_TOKEN:   (req) <6983690570:AAGQR3X-OZku1Ier71SfdE-mOV0fMEFCS8Q>
emby_notifier_tg_1  | TG_CHAT_ID:     (req) <-1001500>
emby_notifier_tg_1  | LOG_LEVEL:      (opt) DEBUG
emby_notifier_tg_1  | LOG_EXPORT:     (opt) False
emby_notifier_tg_1  | LOG_PATH:       (opt) /var/tmp/emby_notifier_tg/
emby_notifier_tg_1  | [2024-05-17 17:04:20] [my_httpd.py|worker|8] [INFO] : Emby Notifier started.
emby_notifier_tg_1  | [2024-05-17 17:04:20] [my_httpd.py|my_httpd|58] [INFO] : HTTP server started at http://localhost:8000
emby_notifier_tg_1  | [2024-05-17 17:05:19] [my_httpd.py|handle_post|23] [DEBUG] : {"Title":"Test Notification","Description":"Test Notification Description","Date":"2024-05-17T09:05:12.1244061Z","Event":"system.notificationtest","Server":{"Name":"飞跃彩虹","Id":"747c7e46274d4415811b9243c7a0753f","Version":"4.8.3.0"}}
emby_notifier_tg_1  | [2024-05-17 17:05:19] [my_httpd.py|worker|11] [DEBUG] : Worker received message:{"Title":"Test Notification","Description":"Test Notification Description","Date":"2024-05-17T09:05:12.1244061Z","Event":"system.notificationtest","Server":{"Name":"飞跃彩虹","Id":"747c7e46274d4415811b9243c7a0753f","Version":"4.8.3.0"}}
emby_notifier_tg_1  | [2024-05-17 17:05:19] [media.py|process_media|214] [INFO] : Received message: Test Notification
emby_notifier_tg_1  | [2024-05-17 17:05:19] [media.py|process_media|216] [WARNING] : Unsupported event type: system.notificationtest

**Comment by Ccccx159** [comment]
注意一下，日志内容里面的 BOT token 和 chat id 没有脱敏哦~

还有我想了解一下，你是如何得出当前报错无法使用这个结论的？我从你的日志中没有看到任何 error 的日志信息。

> emby_notifier_tg_1 | [2024-05-17 17:05:19] [media.py|process_media|216] [WARNING] : Unsupported event type: system.notificationtest

这个 warning 是正常的处理，因为你点击了 Emby Server 控制面板中的测试按钮，对测试事件的一个响应。

Emby Notifier 是针对**新增影片**事件的服务，对媒体库中已经存在的影片是无法感知的。你可以向媒体库中新增一个影片，然后点击控制台中的扫描媒体库 “Scan media library”，触发扫库后，观察 tg 是否正常收到推送消息，如果没有的话，再检查一下日志
