### ISSUE TITLE
docker运行容器遇到错误 自动停止

### ISSUE THREAD

**Issue by aronyfhj** [Ccccx159/Emby_Notifier#17]
024/10/20 09:50:53 | stderr | KeyError: 'username'
-- | -- | --
2024/10/20 09:50:53 | stderr | ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
2024/10/20 09:50:53 | stderr | log.logger.info(f"Telegram getChat successful. Chat User: [{res.json()['result']['username']}], type: {chat_type}")
2024/10/20 09:50:53 | stderr | File "/usr/src/myapp/tgbot.py", line 71, in get_chat
2024/10/20 09:50:53 | stderr | raise e
2024/10/20 09:50:53 | stderr | File "/usr/src/myapp/tgbot.py", line 82, in get_chat
2024/10/20 09:50:53 | stderr | tgbot.get_chat()
2024/10/20 09:50:53 | stderr | File "/usr/src/myapp/main.py", line 106, in require_check
2024/10/20 09:50:53 | stderr | raise e
2024/10/20 09:50:53 | stderr | File "/usr/src/myapp/main.py", line 115, in require_check
2024/10/20 09:50:53 | stderr | require_check()
2024/10/20 09:50:53 | stderr | File "/usr/src/myapp/main.py", line 123, in <module>
2024/10/20 09:50:53 | stderr | Traceback (most recent call last):
2024/10/20 09:50:53 | stderr | [2024-10-20 09:50:53] [main.py\|require_check\|114] [31m[ERROR][37m : 'username'[0m
2024/10/20 09:50:53 | stderr | [2024-10-20 09:50:53] [tgbot.py\|get_chat\|81] [31m[ERROR][37m : Telegram getChat failed. Error: 'username'[0m
2024/10/20 09:50:53 | stderr | [2024-10-20 09:50:53] [tgbot.py\|get_chat\|80] [31m[ERROR][37m : {"method": "getChat", "chat_id": "XXX"}[0m
2024/10/20 09:50:51 | stderr | [2024-10-20 09:50:51] [main.py\|require_check\|105] [32m[INFO][37m : Checking TG_CHAT_ID...[0m
2024/10/20 09:50:51 | stderr | [2024-10-20 09:50:51] [tgbot.py\|bot_authorization\|52] [32m[INFO][37m : Telegram bot authorization successful. Current bot: XXXXX[0m
2024/10/20 09:50:49 | stderr | [2024-10-20 09:50:49] [main.py\|require_check\|101] [32m[INFO][37m : Checking TG_BOT_TOKEN...[0m
2024/10/20 09:50:49 | stderr | [2024-10-20 09:50:49] [tmdb_api.py\|login\|34] [32m[INFO][37m : TMDB login successful.[0m
2024/10/20 09:50:48 | stdout | LOG_PATH:       (opt) /var/tmp/emby_notifier_tg
2024/10/20 09:50:48 | stdout | LOG_EXPORT:     (opt) False
2024/10/20 09:50:48 | stdout | LOG_LEVEL:      (opt) INFO
2024/10/20 09:50:48 | stdout | --------Log info:

**Comment by aronyfhj** [comment]
解决了

**Comment by tao517419** [comment]
> 解决了

怎么解决的呀

**Comment by aronyfhj** [comment]
> > 解决了
> 
> 怎么解决的呀

你tg 上得给自己取个名字  不是帐号

**Comment by tao517419** [comment]
> > > 解决了
> > 
> > 
> > 怎么解决的呀
> 
> 你tg 上得给自己取个名字 不是帐号

好的我试试

**Comment by tao517419** [comment]
> > > > 解决了
> > > 
> > > 
> > > 怎么解决的呀
> > 
> > 
> > 你tg 上得给自己取个名字 不是帐号
> 
> 好的我试试

可以了谢谢
