### ISSUE TITLE
小白不會安裝

### ISSUE THREAD

**Issue by cokebb** [Ccccx159/Emby_Notifier#3]
請問docker Run跟docker-compose是不是選一個安裝?我選擇docker Run指令安裝發送測試服務錯誤,我選擇docker-compose指令安裝就安裝不上....是不是要安裝其他擴展之類???????..謝謝大佬幫幫小弟..........

**Comment by Ccccx159** [comment]
docker run 是一个 Docker CLI 中的命令，用于运行单个 Docker 容器。docker-compose 用于定义和运行多容器 Docker 应用程序的工具，通过一个 docker-compose.yml 文件，可以描述应用程序的服务、网络和卷等配置。

**Comment by cokebb** [comment]
> docker run 是一个 Docker CLI 中的命令，用于运行单个 Docker 容器。docker-compose 用于定义和运行多容器 Docker 应用程序的工具，通过一个 docker-compose.yml 文件，可以描述应用程序的服务、网络和卷等配置。
> 
> 两者选择其一即可。docker run 运行启动后的日志发出来看一下（注意 token, id 等信息脱敏！！！），还有注意一下 Emby Server 中的 webhook URL 填写有误，URL 为 http://<运行 docker 的设备ip>:<端口，默认命令中为8000>

謝謝你的回答原來是兩個容器的命令！還有兩個問題就是TMDB_API_TOKEN是不是API Key還是API 读访问令牌？還有TVDB_API_KEY我沒有這個key不填寫可以嗎？

**Comment by Ccccx159** [comment]
> > docker run 是一个 Docker CLI 中的命令，用于运行单个 Docker 容器。docker-compose 用于定义和运行多容器 Docker 应用程序的工具，通过一个 docker-compose.yml 文件，可以描述应用程序的服务、网络和卷等配置。
> > 两者选择其一即可。docker run 运行启动后的日志发出来看一下（注意 token, id 等信息脱敏！！！），还有注意一下 Emby Server 中的 webhook URL 填写有误，URL 为 http://<运行 docker 的设备ip>:<端口，默认命令中为8000>
> 
> 謝謝你的回答原來是兩個容器的命令！還有兩個問題就是TMDB_API_TOKEN是不是API Key還是API 读访问令牌？還有TVDB_API_KEY我沒有這個key不填寫可以嗎？

**TMDB_API_TOKEN**：API 读访问令牌

**TVDB_API_KEY**：当前实现下是必填的。部分影片 Emby 或者 Jellyfin 推送的信息中可能缺失 TMDB ID，但是存在 TVDB ID（主要发生在新增剧集时）。当前的策略是根据 "影片的名称" + "发布年份" 在 TMDB 中进行搜索，为了提高搜索准确率，我会将搜索结果的 TVDB ID 和 Emby/Jellyfin 推送的 TVDB ID 进行比较，如果相同，则表明当前搜索结果正确，如果始终无法匹配，则返回搜索结果中的第一项。

TVDB ID 也是可以免费申请的：
![image](https://github.com/Ccccx159/Emby_Notifier/assets/35327600/d4a97794-2110-4dcd-b446-c60dae6c237b)

![image](https://github.com/Ccccx159/Emby_Notifier/assets/35327600/f80a97fa-44cb-4959-b52f-0d9cff3d38e4)

注意第二个图中红框部分，下拉选择 第一个，然后这一栏下方会提示当前订阅计划为 ”FREE“ ，下面两个框随便填写一下就能通过了，没记错的话应该是即时生效的

**Comment by cokebb** [comment]
> > > docker run 是一个 Docker CLI 中的命令，用于运行单个 Docker 容器。docker-compose 用于定义和运行多容器 Docker 应用程序的工具，通过一个 docker-compose.yml 文件，可以描述应用程序的服务、网络和卷等配置。
> > > 两者选择其一即可。docker run 运行启动后的日志发出来看一下（注意 token, id 等信息脱敏！！！），还有注意一下 Emby Server 中的 webhook URL 填写有误，URL 为 http://<运行 docker 的设备ip>:<端口，默认命令中为8000>
> > 
> > 
> > 謝謝你的回答原來是兩個容器的命令！還有兩個問題就是TMDB_API_TOKEN是不是API Key還是API 读访问令牌？還有TVDB_API_KEY我沒有這個key不填寫可以嗎？
> 
> **TMDB_API_TOKEN**：API 读访问令牌
> 
> **TVDB_API_KEY**：当前实现下是必填的。部分影片 Emby 或者 Jellyfin 推送的信息中可能缺失 TMDB ID，但是存在 TVDB ID（主要发生在新增剧集时）。当前的策略是根据 "影片的名称" + "发布年份" 在 TMDB 中进行搜索，为了提高搜索准确率，我会将搜索结果的 TVDB ID 和 Emby/Jellyfin 推送的 TVDB ID 进行比较，如果相同，则表明当前搜索结果正确，如果始终无法匹配，则返回搜索结果中的第一项。
> 
> TVDB ID 也是可以免费申请的： ![image](https://private-user-images.githubusercontent.com/35327600/332279067-d4a97794-2110-4dcd-b446-c60dae6c237b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNjU0NzQsIm5iZiI6MTcxNjI2NTE3NCwicGF0aCI6Ii8zNTMyNzYwMC8zMzIyNzkwNjctZDRhOTc3OTQtMjExMC00ZGNkLWI0NDYtYzYwZGFlNmMyMzdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA0MTkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmOGVmMmE0YTIyOWRiMmQwZDNlYmFjYjg0NWMwOGEwOWRkOGI4NDJiNzMzZTMxNTZlNjBhM2QyZGU1Y2YxZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4mscy2VTvR6SAwIRoNg_1hHwdEUJ3R_n7F1SLUmYAUY)
> 
> ![image](https://private-user-images.githubusercontent.com/35327600/332279294-f80a97fa-44cb-4959-b52f-0d9cff3d38e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNjU0NzQsIm5iZiI6MTcxNjI2NTE3NCwicGF0aCI6Ii8zNTMyNzYwMC8zMzIyNzkyOTQtZjgwYTk3ZmEtNDRjYi00OTU5LWI1MmYtMGQ5Y2ZmM2QzOGU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA0MTkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiZTQ5ZWEzNTkzY2U2YjMzNzIyNzllYjc4NTBkZWM4YmI0M2E2YmI4YzBlMDllNWVlZjQ0NTZmNzBmN2IxMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OFhBkb2PW0DIF--31t1_shpQ4GjPl2cIEyiycJn_4vA)
> 
> 注意第二个图中红框部分，下拉选择 第一个，然后这一栏下方会提示当前订阅计划为 ”FREE“ ，下面两个框随便填写一下就能通过了，没记错的话应该是即时生效的

今晚回家試試，那我應該是TVDB ID key沒填寫可能导致連接服務器錯誤的問題。謝謝大佬詳細教導

**Comment by cokebb** [comment]
請問大佬Notifier日志怎麼查看??我用docker run安裝...可以發送通知測試...但好像機械人沒反應....我把機械人拉入群組設置管理員..
是不是機械人需要設置什麼?

**Comment by Ccccx159** [comment]
docker 容器日志查看方式请自行 google，这里不提供基础教学哈

**Comment by cokebb** [comment]
> docker 容器日志查看方式请自行 google，这里不提供基础教学哈

看了日誌發送成功.........可惜有錯誤地方....大佗看看圖是什麼問題
![QQ图片20240522205343](https://github.com/Ccccx159/Emby_Notifier/assets/73053501/cde67bf2-5aca-460d-8c32-70689f1b9486)

**Comment by Ccccx159** [comment]
你的chat id有问题，telegram返回了错误，提示 chat not found。日志显示chat id是COKEMV_bot，这个如果是你填充的chat id的话，肯定是不对的。你google一下如何获取chat id ，可以是和机器人对话的chat id ，也可以是机器人具有发送消息权限的channel的chat id。

**Comment by cokebb** [comment]
> **TVDB_API_KEY**：当前实现下是必填的。部分影片 Emby 或者 Jellyfin 推送的信息中可能缺失 TMDB ID，但是存在 TVDB ID（主要发生在新增剧集时）。当前的策略是根据 "影片的名称" + "发布年份" 在 TMDB 中进行搜索，为了提高搜索准确率，我会将搜索结果的 TVDB ID 和 Emby/Jellyfin 推送的 TVDB ID 进行比较，如果相同，则表明当前搜索结果正确，如果始终无法匹配，则返回搜索结果中的第一项。

終於弄好了~謝謝大佬的指點~
