### ISSUE TITLE
可以支持微信应用吗

### ISSUE THREAD

**Issue by behinder85** [Ccccx159/Emby_Notifier#4]
TG国内不是那么经常使用
如果可以的话，麻烦作者支持一下企业微信应用/自定义webhook

**Comment by Ccccx159** [comment]
> TG国内不是那么经常使用 如果可以的话，麻烦作者支持一下企业微信应用/自定义webhook

后续可以支持企业微信，可能会花点时间。

自定义webhook的需求能详细描述一下吗？是想注册一个 webhook 到 Emby Notifier，Emby Notifier 将原本发送给 bot 的消息转发到 webhook 上，然后通过这个自定义的 webhook 进行二次转发是吗？如果只是这样的话，应该问题不大，不过需要定义一下协议。而且我目前还不清楚 tgbot 和微信的 bot 发送数据的差异在哪里，这个可能会在完成企业微信支持后再考虑

**Comment by Ccccx159** [comment]
预计下周五前更新，将支持企业微信的应用消息推送!

应用的消息卡片效果预计如下：

![image](https://github.com/Ccccx159/Emby_Notifier/assets/35327600/0a26815d-859f-4d63-924a-693d269d1700)

![image](https://github.com/Ccccx159/Emby_Notifier/assets/35327600/8ea6dbb0-30c0-4e17-b1a2-f46f40927130)
