### ISSUE TITLE
启动报错    log.logger.info(f"Telegram getChat successful. Chat title: [{res.json()['result']['title']}], type: {res.json()['result']['type']}")

### ISSUE THREAD

**Issue by 907739769** [Ccccx159/Emby_Notifier#5]
[2024-06-09 21:35:13] [main.py|require_check|81] [ERROR] : 'title'
Traceback (most recent call last):
  File "/usr/src/myapp/main.py", line 90, in <module>
    require_check()
  File "/usr/src/myapp/main.py", line 82, in require_check
    raise e
  File "/usr/src/myapp/main.py", line 79, in require_check
    tgbot.get_chat()
  File "/usr/src/myapp/tgbot.py", line 76, in get_chat
    raise e
  File "/usr/src/myapp/tgbot.py", line 69, in get_chat
    log.logger.info(f"Telegram getChat successful. Chat title: [{res.json()['result']['title']}], type: {res.json()['result']['type']}")
                                                                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'title'

**Comment by 907739769** [comment]
可选参数tvdb没填  报错
Welcome to Emby Notifier!
Author: xu4n_ch3n
Version: 2.2.0
Update Time: 2024-05-24
Description: Emby Notifier is a media notification service for Emby Server. Now Jellyfin Server is alreay supported.
Repository: https://github.com/Ccccx159/Emby_Notifier
Checking environment variables...
TMDB_API_TOKEN: (req) eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI4YTFjMWFiMmYyN2IwNzc5YzdjMjY4ODE2YjYyMWZjYSIsInN1YiI6IjYxZTRkYjc4OTA0ZjZkMDA0MjU1MTM3NSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.Paxpf40iJF_xFAPs5UhQYj8bDD_P5nns4QQuO-Q6mS0
TVDB_API_KEY:   (opt) None
TG_BOT_TOKEN:   (req) 74766G5RQC7xxxI9ENz9XZ3b_t8
TG_CHAT_ID:     (req) 51xxx6
LOG_LEVEL:      (opt) INFO
LOG_EXPORT:     (opt) False
LOG_PATH:       (opt) /var/tmp/emby_notifier_tg/
ERROR!!! Please set the required environment variables, and restart the service.

**Comment by Ccccx159** [comment]
看你第一条发的，貌似是telegram的chat id不正确，返回结果里面没有title 字段

**Comment by Ccccx159** [comment]
如果 chat id 没有问题的话，请将日志等级设置为DEBUG，然后重新启动后提供更多得日志

**Comment by 907739769** [comment]
Welcome to Emby Notifier!
Author: xu4n_ch3n
Version: 2.2.0
Update Time: 2024-05-24
Description: Emby Notifier is a media notification service for Emby Server. Now Jellyfin Server is alreay supported.
Repository: https://github.com/Ccccx159/Emby_Notifier
Checking environment variables...
TMDB_API_TOKEN: (req) eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI4YTFjMWFiMmYyN2IwNzc5YzdjMjY4ODE2YjYyMWZjYSIsInN1YiI6IjYxZTRkYjc4OTA0ZjZkMDA0MjU1MTM3NSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.Paxpf40iJF_xFAPs5UhQYj8bDD_P5nns4QQuO-Q6mS0
TVDB_API_KEY:   (opt) None
TG_BOT_TOKEN:   (req) 7476680xxxb_t8
TG_CHAT_ID:     (req) 51xxxx46
LOG_LEVEL:      (opt) DEBUG
LOG_EXPORT:     (opt) False
LOG_PATH:       (opt) /var/tmp/emby_notifier_tg/
ERROR!!! Please set the required environment variables, and restart the service.

**Comment by 907739769** [comment]
> 如果 chat id 没有问题的话，请将日志等级设置为DEBUG，然后重新启动后提供更多得日志

chatid我用的用户id    别的tg通知我也是填的用户ID  没有用频道  就用机器人的单聊通知

**Comment by Ccccx159** [comment]
> > 如果 chat id 没有问题的话，请将日志等级设置为DEBUG，然后重新启动后提供更多得日志
> 
> chatid我用的用户id 别的tg通知我也是填的用户ID 没有用频道 就用机器人的单聊通知

我测试了一下，如果 chat_id 填写的是 bot 或 用户 id，在校验过程中会存在校验通过，但是由于此时 tg 返回的结果和填充 channel id 不同而导致的失败问题。*此问题我会在下个 patch 中进行修复*。

同时我也测试了消息发送的流程，如果期望 bot 单独给你个人发送消息的话，chat id 需要填充你自己的 **个人用户 id**，请确保这一点。

**Comment by Ccccx159** [comment]
预计在下周二或周三进行修复

**Comment by shmily1866** [comment]
> 预计在下周二或周三进行修复

我也是用的用户id，怪不得总失败，等佬修复

**Comment by Ccccx159** [comment]
docker hub 镜像已推送更新，新版本在校验过程中会向 chat id 所指对象发送版本信息，当前版本为 v2.2.2，请注意核对版本。使用过程中有任何问题，欢迎反馈~

**Comment by 907739769** [comment]
修复了 感谢
