### ISSUE TITLE
能支持一下arm的吗，甲骨文的emby弄不上去~

### ISSUE THREAD

**Issue by 3377** [Ccccx159/Emby_Notifier#7]

**Comment by Ccccx159** [comment]
我目前没有arm环境，过几天用r2s搭一个测试环境验证一下看看。测试通过了我会在这里回复🧐

**Comment by 3377** [comment]
r2s也是and吧，我临时用amd的搭建成功了，能不能给其他的通知功能加上吗，目前用script-x 不是很方便



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Rookie Chen ***@***.***&gt;
发送时间: 2024年7月14日 10:15
收件人: Ccccx159/Emby_Notifier ***@***.***&gt;
抄送: 3377 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Ccccx159/Emby_Notifier] 能支持一下arm的吗，甲骨文的emby弄不上去~ (Issue #7)

**Comment by Ccccx159** [comment]
r2s应该是armv8，aarch64的架构，我之前用来做op的。你说的其他通知是指Emby的其他类型事件的通知还是什么？

**Comment by 3377** [comment]
其他通知功能，比如类似这个https://github.com/AnthonyMusgrove/Emby-ScripterX。
我目前用的是这个，基于小雅全家桶。不过经常乱跳，体验不是很好。

**Comment by Ccccx159** [comment]
你说的其他通知，就是其他的事件通知，比如开始播放，添加用户这种？全事件通知对于个人媒体服务器的必要性感觉不是很强呢，可能后续会增加一些事件的通知。不过短期内对这个功能应该不会进行扩展。

至于arm的支持可能会在两个礼拜内完成，不过不能保证，因为近期工作比较忙，可能空余时间有些

**Comment by Ccccx159** [comment]
`docker pull b1gfac3c4t/emby_notifier_tg:aarch64`

aarch64 的 arm 架构 docker image 已推送至 hub，有需要可进行测试使用，目前基于 v3.0.1 进行打包测试， 本地树莓派 4B 设备测试无误
