### ISSUE TITLE
win版docker新建时显示No ports exposed in this image，导致emby通知填写端口后显示"发送通知时出错  由于目标计算机积极拒绝，无法连接。 (192.168.1.5:8000)"，请问这种该怎么办呢？

### ISSUE THREAD

**Issue by jerryshen2022** [Ccccx159/Emby_Notifier#9]

**Comment by Ccccx159** [comment]
我都是在 Linux 环境打包的，Windows docker desktop 那个如果要显示端口配置的话可能要单独另外适配。你可以在windows的cmd中运行容器。打开cmd，然后复制下面命令到cmd中，回车执行：

```bat
docker run -d --name=emby-notifier-tg --restart=unless-stopped ^
    -e TMDB_API_TOKEN=你的TMDB API Token ^
    -e TG_BOT_TOKEN=你的电报机器人Token ^
    -e TG_CHAT_ID=你的电报chat id ^
    -p 8000:8000 ^
    b1gfac3c4t/emby_notifier_tg:latest
```

docker desktop 的 container 中应该就能看到运行的容器了，然后你再去 emby server 中试试。

嫌麻烦的话：
1. 在桌面新建文本文档
2. 把上面的命令复制进去
3. 把对应的内容修改完成，保存文件
4. 修改文件后缀，改成 "bat"，弹出的提示选确定修改
5. 双击这个文件即可

**Comment by Ccccx159** [comment]
研究了一下，只需要在构建镜像的时候暴露端口就能在 docker desktop 中进行配置了，后面我改一下构建文件好了。不过目前应该不影响使用～
